language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t sandeepb3245/mywebsite .
  
after_success:
  # log in to docker hub account
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  # now push the above build images to docker hub
  - docker push sandeepb3245/mywebsite